site_name: Online-Judge

nav:
  - Sobre: index.md
  - Atas:
      - Planejamento:
          - Ata Primeira Reunião: atas/planejamento/reuniao-1.md
          - Ata Segunda Reunião: atas/planejamento/reuniao-2.md
      - Análise de Requisitos:
          - Ata Terceira Reunião: atas/analise-de-req/reuniao-3.md
          - Ata Quarta Reunião: atas/analise-de-req/reuniao-4.md
          - Ata Quinta Reunião: atas/analise-de-req/reuniao-5.md
          - Ata Sexta Reunião: atas/analise-de-req/reuniao-6.md
          - Ata Oitava Reunião: atas/analise-de-req/reuniao-8.md
      - Verificação:
          - Ata Sétima Reunião: atas/verificacao/reuniao-7.md

  - Planejamento:
      - Apresentação: primeira-entrega/apresentacao.md
      - Equipe: primeira-entrega/equipe.md
      - Sites Avaliados: primeira-entrega/sites-avaliados.md
      - Site Escolhido: primeira-entrega/site-escolhido.md
      - Metodologia: primeira-entrega/metodologia.md
      - Ferramentas do Projeto: primeira-entrega/ferramentas.md
      - Processo de Design: primeira-entrega/processo-design.md
      - Cronograma das Atividades: primeira-entrega/cronograma-atividades.md
  - Análise de Requisitos I:
      - Apresentação: segunda-entrega/apresentacao.md
      - Análise de Tarefas:
          - Análise Hierárquica de Tarefas (HTA): segunda-entrega/analise-tarefas/HTA.md
          - GOMS: segunda-entrega/analise-tarefas/GOMS.md
      - Aspectos Éticos: segunda-entrega/aspectos-eticos.md
      - Perfil de Usuário: segunda-entrega/perfil-usuario.md
      - Personas: segunda-entrega/personas.md
      - Cenários: segunda-entrega/cenarios.md
  - Análise de Requisitos II:
      - Apresentação: terceira-entrega/apresentacao.md
      - Metas de Usabilidade: terceira-entrega/metas-usabilidade.md
      - Características da Plataforma: terceira-entrega/caracteristicas-plataforma.md
      - Princípios Gerais do Projeto: terceira-entrega/principios-gerais.md
      - Guia de Estilo: terceira-entrega/guia-estilo.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Apresentação: quarta-entrega/nivel1/apresentacao.md
          - Storyboard:
              - Storyboards da equipe: quarta-entrega/nivel1/storyboard/storyboards.md
              - Planejamento da Avaliação de Storyboard: quarta-entrega/nivel1/storyboard/planejamento-avaliacao-storyboard.md
              - Planejamento do Relato dos Resultados - Storyboard: quarta-entrega/nivel1/storyboard/planejamento-relato-resultados-storyboard.md
              - Relato dos Resultados do StoryBoard: quarta-entrega/nivel1/storyboard/relato-resultados-storyboard.md
          - Análise Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: quarta-entrega/nivel1/analise_de_tarefas/planejamento-avaliacao-tarefas.md
              - Planejamento do Relato dos Resultados: quarta-entrega/nivel1/analise_de_tarefas/planejamento-do-relato-dos-resultados.md
              - Relato dos Resultados da Análise de Tarefas: quarta-entrega/nivel1/analise_de_tarefas/relato-resultados-tarefas.md
      - Nível 2:
          - Apresentação: quarta-entrega/nivel2/apresentacao.md
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: quarta-entrega/nivel2/planejamento-avaliacao-prototipo-papel.md
              - Planejamento do Relato dos Resultados do Protótipo de Papel: quarta-entrega/nivel2/planejamento-do-relato-dos-resultados-prototipo-de-papel.md
              - Relato dos Resultados do Protótipo de papel: quarta-entrega/nivel2/relato-dos-resultados-do-protótipo-de-papel.md
      - Nível 3:
            - Apresentação: quarta-entrega/nivel3/apresentacao.md
          - Protótipo de Alta Fidelidade:
              - Planejamento da Avaliação do Protótipo de Alta Fidelidade: quarta-entrega/nivel3/planejamento-avaliacao-prototipo-alta-fidelidade.md
              - Planejamento do Relato dos resultados do Protótipo de Alta Fidelidade: quarta-entrega/nivel3/planejamento-relato-dos-resultados-prototipo-alta.md

  - Verificação do Grupo 8:
      - Apresentação: verificacao/grupo_8/apresentacao/apresentacao.md
      - Etapa 1:
          - Planejamento da Verificação da Etapa 1: verificacao/grupo_8/etapa_1/planejamento-verificacao.md
          - Cronograma: verificacao/grupo_8/etapa_1/verificacao-cronograma.md
          - Ferramentas: verificacao/grupo_8/etapa_1/verificacao-ferramentas.md
          - Processo de Design: verificacao/grupo_8/etapa_1/verificacao-processo-design.md
          - Site Escolhido: verificacao/grupo_8/etapa_1/verificacao-site-escolhido.md
      - Etapa 2:
          - Planejamento da Verificação da Etapa 2: verificacao/grupo_8/etapa_2/planejamento-verificacao.md
          - Análise de Tarefas: verificacao/grupo_8/etapa_2/verificacao-analise-de-tarefas.md
          - Aspectos Éticos: verificacao/grupo_8/etapa_2/verificacao-aspectos-eticos.md
          - Perfil de Usuário: verificacao/grupo_8/etapa_2/verificacao-perfil-de-usuario.md
          - Personas: verificacao/grupo_8/etapa_2/verificacao-personas.md
          - Cenários: verificacao/grupo_8/etapa_2/verificacao-cenarios.md
      - Etapa 3:
          - Planejamento da Verificação da Etapa 3: verificacao/grupo_8/etapa_3/planejamento-verificacao.md
          - Metas de Usabilidade: verificacao/grupo_8/etapa_3/metas-de-usabilidade.md
          - Características da Plataforma: verificacao/grupo_8/etapa_3/caracteristicas-gerais.md
          - Princípios Gerais do Projeto: verificacao/grupo_8/etapa_3/principios-gerais.md
          - Guia de Estilo: verificacao/grupo_8/etapa_3/guia-de-estilo.md
      - Etapa 4:
          - Planejamento da Verificação da Etapa 4: verificacao/grupo_8/etapa_4/planejamento-verificacao.md
          - Planejamento da Avaliação da Análise de Tarefas: verificacao/grupo_8/etapa_4/planejamento-analise-tarefas.md
          - Planejamento da Avaliação do Storyboard: verificacao/grupo_8/etapa_4/planejamento-storyboards.md
          - Planejamento do Relato dos Resultados da Avaliação da Análise de Tarefas: verificacao/grupo_8/etapa_4/planejamento-resultados-analise-tarefas.md
          - Planejamento da Relato dos Resultados da Avaliação do Storyboard: verificacao/grupo_8/etapa_4/planejamento-resultados-storyboards.md
          - Verificação dos Storyboards: verificacao/grupo_8/etapa_4/verificacao-storyboards.md
      - Etapa 5:
          - Planejamento da verificação da Etapa 5: verificacao/grupo_8/etapa_5/planejamento-verificacao.md
          - Verificação do planejamento da avaliação do Protótipo de Papel: verificacao/grupo_8/etapa_5/verificacao-planejamento-avaliacao-do-prototipo-papel.md
          - Verificação do planejamento do relato da avaliação do Protótipo de Papel: verificacao/grupo_8/etapa_5/verificacao-planejamento-relato-avaliacao-prototipo-papel.md
          - Verificação do relato dos resultados do StoryBoard e da Análise de Tarefas: verificacao/grupo_8/etapa_5/verificacao-relato-dos-resultados-storyboard-e-analise.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: amber
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo claro

  language: pt-BR
  favicon: assets/images/onlinejudge-logo.png
  logo: assets/images/onlinejudge-logo.png
