site_name: Online-Judge

nav:
  - Sobre: index.md
  - Atas:
      - Primeira entrega:
          - Ata primeira reunião: atas/primeira-entrega/reuniao-1.md
          - Ata segunda reunião: atas/primeira-entrega/reuniao-2.md
  - Primeira Entrega:
      - Apresentação: primeira-entrega/apresentacao.md
      - Equipe: primeira-entrega/equipe.md
      - Sites Avaliados:
          - Escola Virtual: primeira-entrega/sites-avaliados/site-escola-virtual.md
          - Ministério da Saúde: primeira-entrega/sites-avaliados/site-ministerio-saude.md
          - Governo do Distrito Federal (Henrique): primeira-entrega/sites-avaliados/site-gdf-henrique.md
          - Governo do Distrito Federal (Kallyne): primeira-entrega/sites-avaliados/site-gdf-kallyne.md
          - IBAMA: primeira-entrega/sites-avaliados/site-ibama.md
          - Detran DF: primeira-entrega/sites-avaliados/site-detran-df.md
          - Governo de Alagoas: primeira-entrega/sites-avaliados/site-governo-alagoas.md
      - Site Avaliado: primeira-entrega/site-escolhido.md
      - Metodologia: primeira-entrega/metodologia.md
      - Ferramentas do Projeto: primeira-entrega/ferramentas.md
      - Processo de Design: primeira-entrega/processo-design.md
      - Cronograma das Atividades: primeira-entrega/cronograma-atividades.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: amber
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo claro

  language: pt-BR
  favicon: assets/images/onlinejudge-logo.png
  logo: assets/images/onlinejudge-logo.png
