site_name: Online-Judge

nav:
    - Sobre: index.md
    - Atas:
      - Primeira Entrega:
          - Ata Primeira Reunião: atas/primeira-entrega/reuniao-1.md
          - Ata Segunda Reunião: atas/primeira-entrega/reuniao-2.md
      - Segunda Entrega:
          - Ata Terceira Reunião: atas/segunda-entrega/reuniao-3.md
      - Terceira Entrega:
          - Ata Quarta Reunião: atas/terceira-entrega/reuniao-4.md
      - Quarta Entrega:
          - Ata Quinta Reunião: atas/quarta-entrega/reuniao-5.md
      - Quinta Entrega:
          - Ata Sexta Reunião: atas/quinta-entrega/reuniao-6.md

    - Planejamento:
      - Apresentação: primeira-entrega/apresentacao.md
      - Equipe: primeira-entrega/equipe.md
      - Sites Avaliados: primeira-entrega/sites-avaliados.md
      - Site Escolhido: primeira-entrega/site-escolhido.md
      - Metodologia: primeira-entrega/metodologia.md
      - Ferramentas do Projeto: primeira-entrega/ferramentas.md
      - Processo de Design: primeira-entrega/processo-design.md
      - Cronograma das Atividades: primeira-entrega/cronograma-atividades.md
    - Análise de Requisitos I:
      - Apresentação: segunda-entrega/apresentacao.md
      - Análise de Tarefas:
          - Análise Hierárquica de Tarefas (HTA): segunda-entrega/analise-tarefas/HTA.md
          - GOMS: segunda-entrega/analise-tarefas/GOMS.md
      - Aspectos Éticos: segunda-entrega/aspectos-eticos.md
      - Perfil de Usuário: segunda-entrega/perfil-usuario.md
      - Personas: segunda-entrega/personas.md
      - Cenários: segunda-entrega/cenarios.md
    - Análise de Requisitos II:
      - Apresentação: terceira-entrega/apresentacao.md
      - Metas de Usabilidade: terceira-entrega/metas-usabilidade.md
      - Características da Plataforma: terceira-entrega/caracteristicas-plataforma.md
      - Princípios Gerais do Projeto: terceira-entrega/principios-gerais.md
      - Guia de Estilo: terceira-entrega/guia-estilo.md
    - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Storyboard:
              - Storyboards da equipe: quarta-entrega/nivel1/storyboard/storyboards.md
              - Planejamento da Avaliação de Storyboard: quarta-entrega/nivel1/storyboard/planejamento-avaliacao-storyboard.md
              - Planejamento do Relato dos Resultados - Storyboard: quarta-entrega/nivel1/storyboard/planejamento-relato-resultados-storyboard.md
              - Relato dos Resultados do StoryBoard: quarta-entrega/nivel1/storyboard/relato-resultados-storyboard.md
          - Análise Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: quarta-entrega/nivel1/analise_de_tarefas/planejamento-avaliacao-tarefas.md
              - Planejamento do Relato dos Resultados: quarta-entrega/nivel1/analise_de_tarefas/planejamento-do-relato-dos-resultados.md
              - Relato dos Resultados da Análise de Tarefas: quarta-entrega/nivel1/analise_de_tarefas/relato-resultados-tarefas.md
      - Nível 2:
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: quarta-entrega/nivel2/planejamento-avaliacao-prototipo-papel.md
              - Planejamento do Relato dos Resultados - Protótipo de Papel: quarta-entrega/nivel2/planejamento-do-relato-dos-resultados-prototipo-de-papel.md
    - Verificação do Grupo 8:
        - Etapa 4:
            - Planejamento da verificação da etapa 4: verificacao/grupo_8/etapa_4/planejamento-verificacao-etapa-4.md
    
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: amber
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/circle-half-full
        name: Alterar para o modo claro

  language: pt-BR
  favicon: assets/images/onlinejudge-logo.png
  logo: assets/images/onlinejudge-logo.png
